version: '3.7'

services:
  db:
    image: postgres:11.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  auth_api:
    restart: always
    build: .
    command: python /whatsonme/manage.py runserver 0.0.0.0:8000
    # command: bash -c "
    #   python /whatsonme/manage.py makemigrations
    #   && python /whatsonme/manage.py migrate
    #   && python /whatsonme/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/whatsonme
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: